version: '3'
services:
  my_container:
    image: my_image
    volumes:
      - /home/alonkay/Thesis/sequences:/home/alonkay/app/sequences
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    command: python3 Main.py
